package com.coinMall.dao;

import java.util.List;

import com.coinMall.pojo.Category;

public interface CategoryMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_category
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_category
	 * @mbg.generated
	 */
	int insert(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_category
	 * @mbg.generated
	 */
	int insertSelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_category
	 * @mbg.generated
	 */
	Category selectByPrimaryKey(Integer categoryId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_category
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_category
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Category record);

	/**
     *       根据    层级查找所有有的   商品分类信息
     * @param categoryLevel
     * @return
     */
	List<Category> getCategorysByLevel(Integer categoryLevel);

	/**
	 *         得到所有的分类标题   名字
	 * @return
	 */
	List<String> getAllTitle();

	/***
	 *     根据层级    查询是否有   子类
	 * @param categoryId
	 * @return
	 */
	Integer haveSonCategory(Integer categoryId);
	
	
	/***
	 *   我们   根据   分类  ID  得到它所有的子类Id
	 * @param categoryId
	 * @return
	 */
	List<Category> getAllSonCategory(Integer categoryId);
	
	
}











