package com.coinMall.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.coinMall.pojo.Comment;

public interface CommentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_comment
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_comment
	 * @mbg.generated
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_comment
	 * @mbg.generated
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_comment
	 * @mbg.generated
	 */
	Comment selectByPrimaryKey(Long commentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_comment
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_comment
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Comment record);

	/**
     * 加减点赞总数
     * @param number
     * @param commentId
     * @return
     */
    int updatePraiseTotal(@Param("number")Integer number, @Param("commentId")Long commentId);
    
    /**
     * 加减回复总数
     * @param number
     * @param commentId
     * @return
     */
    int updateReplyTotal(@Param("number")Integer number, @Param("commentId")Long commentId);
    
    /**
     * 评论列表
     * @param uid
     * @param aboutId
     * @param parentId
     * @param pageIndex
     * @param pageSize
     * @return
     */
    List<Comment> getCommentList(@Param("aboutId")String aboutId, @Param("uid")Integer uid, @Param("parentId")Long parentId, @Param("pageIndex")Integer pageIndex, @Param("pageSize")Integer pageSize);
    
    /**
     * 评论列表统计
     * @param aboutId
     * @param parentId
     * @return
     */
    int getCommentListCount(@Param("aboutId")String aboutId, @Param("parentId")Long parentId);
    
    /**
     * 查询主评论详情
     * @param uid
     * @param commentId
     * @return
     */
    Comment getParentCommentById(@Param("uid")Integer uid, @Param("commentId")Long commentId);
}