package com.coinMall.dao;

import java.util.List;

import com.coinMall.pojo.GoodsImages;

public interface GoodsImagesMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_images
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer imagesId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_images
	 * @mbg.generated
	 */
	int insert(GoodsImages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_images
	 * @mbg.generated
	 */
	int insertSelective(GoodsImages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_images
	 * @mbg.generated
	 */
	GoodsImages selectByPrimaryKey(Integer imagesId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_images
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GoodsImages record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_goods_images
	 * @mbg.generated
	 */
	int updateByPrimaryKey(GoodsImages record);

	/***
     *  	查询我们  图片排序�?  �?大�??  
     * @param goodsId 
     * @return
     */
	Integer selectMaxSort(Long goodsId);

	/**
	 *     根据商品ID 查询  商品�?有的图片
	 * @param goodsId
	 * @return
	 */
	List<GoodsImages> selectByGoodsId(Long goodsId);
}


















