package com.coinMall.dao;

import java.util.List;

import com.coinMall.pojo.GoodsInfo;

public interface GoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    GoodsInfo selectByPrimaryKey(Long goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsInfo record);
    
    
    /***
     *    得到商品      列表 
     * @return
     */
	List<GoodsInfo> getGoodsList();
}