package com.coinMall.dao;

import java.util.List;

import com.coinMall.pojo.PlatformInfo;

public interface PlatformInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer platformId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_info
     *
     * @mbg.generated
     */
    int insert(PlatformInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_info
     *
     * @mbg.generated
     */
    int insertSelective(PlatformInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_info
     *
     * @mbg.generated
     */
    PlatformInfo selectByPrimaryKey(Integer platformId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformInfo record);

	List<PlatformInfo> selectAll();
}