package com.coinMall.dao;

import com.coinMall.pojo.PlatformRechargeLog;

public interface PlatformRechargeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_recharge_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_recharge_log
     *
     * @mbg.generated
     */
    int insert(PlatformRechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_recharge_log
     *
     * @mbg.generated
     */
    int insertSelective(PlatformRechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_recharge_log
     *
     * @mbg.generated
     */
    PlatformRechargeLog selectByPrimaryKey(Integer rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_recharge_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlatformRechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_platform_recharge_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlatformRechargeLog record);
}