package com.coinMall.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.coinMall.pojo.ReceiptInfo;

public interface ReceiptInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_receipt_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer receiptId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_receipt_info
	 * @mbg.generated
	 */
	int insert(ReceiptInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_receipt_info
	 * @mbg.generated
	 */
	int insertSelective(ReceiptInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_receipt_info
	 * @mbg.generated
	 */
	ReceiptInfo selectByPrimaryKey(Integer receiptId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_receipt_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(ReceiptInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_receipt_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(ReceiptInfo record);

	/**
     * 收货地址列表
     * @param uid
     * @return
     */
    List<ReceiptInfo> getReceiptInfoList(@Param("uid")Integer uid);
    
    /**
     * 统计个人收货地址总数
     * @param uid
     * @return
     */
    int getReceiptInfoCountByUid(@Param("uid")Integer uid);
    
    /**
     * 查询默认收货地址
     * @param uid
     * @return
     */
    ReceiptInfo getReceiptDefaultByUid(@Param("uid")Integer uid);
}