package com.coinMall.dao;

import com.coinMall.pojo.Reply;

public interface ReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_reply
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long replyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_reply
	 * @mbg.generated
	 */
	int insert(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_reply
	 * @mbg.generated
	 */
	int insertSelective(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_reply
	 * @mbg.generated
	 */
	Reply selectByPrimaryKey(Long replyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_reply
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_reply
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Reply record);

}