package com.coinMall.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.coinMall.pojo.ShopCart;

public interface ShopCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int insert(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int insertSelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    ShopCart selectByPrimaryKey(Long cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shop_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCart record);
    
    /**
     * 根据用户id,商品id,规格id查询
     * @param uid
     * @param goodsId
     * @param stockId
     * @return
     */
    ShopCart getShopCartByMultiId(@Param("uid")Integer uid, @Param("goodsId")Long goodsId, @Param("stockId")Long stockId);
    
    /**
     * 根据用户id查询购物车列表
     * @param uid
     * @return
     */
    List<ShopCart> getShopCartListByUid(@Param("uid")Integer uid);
    
    /**
     * 加减购物车商品数量
     * @param cartId
     * @param number
     * @return
     */
    int updateCartTotalById(@Param("cartId")Long cartId, @Param("number")Integer number);
}