package com.coinMall.pojo;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_id
	 * @mbg.generated
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_name
	 * @mbg.generated
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_title
	 * @mbg.generated
	 */
	private String categoryTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_sort
	 * @mbg.generated
	 */
	private Integer categorySort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_display
	 * @mbg.generated
	 */
	private Short categoryDisplay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_parent_id
	 * @mbg.generated
	 */
	private Integer categoryParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_category.category_level
	 * @mbg.generated
	 */
	private Integer categoryLevel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_id
	 * @return  the value of t_category.category_id
	 * @mbg.generated
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_id
	 * @param categoryId  the value for t_category.category_id
	 * @mbg.generated
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_name
	 * @return  the value of t_category.category_name
	 * @mbg.generated
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_name
	 * @param categoryName  the value for t_category.category_name
	 * @mbg.generated
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName == null ? null : categoryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_title
	 * @return  the value of t_category.category_title
	 * @mbg.generated
	 */
	public String getCategoryTitle() {
		return categoryTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_title
	 * @param categoryTitle  the value for t_category.category_title
	 * @mbg.generated
	 */
	public void setCategoryTitle(String categoryTitle) {
		this.categoryTitle = categoryTitle == null ? null : categoryTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_sort
	 * @return  the value of t_category.category_sort
	 * @mbg.generated
	 */
	public Integer getCategorySort() {
		return categorySort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_sort
	 * @param categorySort  the value for t_category.category_sort
	 * @mbg.generated
	 */
	public void setCategorySort(Integer categorySort) {
		this.categorySort = categorySort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_display
	 * @return  the value of t_category.category_display
	 * @mbg.generated
	 */
	public Short getCategoryDisplay() {
		return categoryDisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_display
	 * @param categoryDisplay  the value for t_category.category_display
	 * @mbg.generated
	 */
	public void setCategoryDisplay(Short categoryDisplay) {
		this.categoryDisplay = categoryDisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_parent_id
	 * @return  the value of t_category.category_parent_id
	 * @mbg.generated
	 */
	public Integer getCategoryParentId() {
		return categoryParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_parent_id
	 * @param categoryParentId  the value for t_category.category_parent_id
	 * @mbg.generated
	 */
	public void setCategoryParentId(Integer categoryParentId) {
		this.categoryParentId = categoryParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_category.category_level
	 * @return  the value of t_category.category_level
	 * @mbg.generated
	 */
	public Integer getCategoryLevel() {
		return categoryLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_category.category_level
	 * @param categoryLevel  the value for t_category.category_level
	 * @mbg.generated
	 */
	public void setCategoryLevel(Integer categoryLevel) {
		this.categoryLevel = categoryLevel;
	}
}