package com.coinMall.pojo;

import java.util.Date;

public class Comment {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.comment_id
	 * @mbg.generated
	 */
	private Long commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.source_id
	 * @mbg.generated
	 */
	private Integer sourceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.about_id
	 * @mbg.generated
	 */
	private String aboutId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.parent_id
	 * @mbg.generated
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.comment_time
	 * @mbg.generated
	 */
	private Date commentTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.comment_ip
	 * @mbg.generated
	 */
	private String commentIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.ip_area
	 * @mbg.generated
	 */
	private String ipArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.comment_content
	 * @mbg.generated
	 */
	private String commentContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.comment_images
	 * @mbg.generated
	 */
	private String commentImages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.have_images
	 * @mbg.generated
	 */
	private Integer haveImages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.comment_status
	 * @mbg.generated
	 */
	private Integer commentStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.reply_total
	 * @mbg.generated
	 */
	private Integer replyTotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_comment.praise_total
	 * @mbg.generated
	 */
	private Integer praiseTotal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.comment_id
	 * @return  the value of t_comment.comment_id
	 * @mbg.generated
	 */
	public Long getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.comment_id
	 * @param commentId  the value for t_comment.comment_id
	 * @mbg.generated
	 */
	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.source_id
	 * @return  the value of t_comment.source_id
	 * @mbg.generated
	 */
	public Integer getSourceId() {
		return sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.source_id
	 * @param sourceId  the value for t_comment.source_id
	 * @mbg.generated
	 */
	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.about_id
	 * @return  the value of t_comment.about_id
	 * @mbg.generated
	 */
	public String getAboutId() {
		return aboutId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.about_id
	 * @param aboutId  the value for t_comment.about_id
	 * @mbg.generated
	 */
	public void setAboutId(String aboutId) {
		this.aboutId = aboutId == null ? null : aboutId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.uid
	 * @return  the value of t_comment.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.uid
	 * @param uid  the value for t_comment.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.parent_id
	 * @return  the value of t_comment.parent_id
	 * @mbg.generated
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.parent_id
	 * @param parentId  the value for t_comment.parent_id
	 * @mbg.generated
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.comment_time
	 * @return  the value of t_comment.comment_time
	 * @mbg.generated
	 */
	public Date getCommentTime() {
		return commentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.comment_time
	 * @param commentTime  the value for t_comment.comment_time
	 * @mbg.generated
	 */
	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.comment_ip
	 * @return  the value of t_comment.comment_ip
	 * @mbg.generated
	 */
	public String getCommentIp() {
		return commentIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.comment_ip
	 * @param commentIp  the value for t_comment.comment_ip
	 * @mbg.generated
	 */
	public void setCommentIp(String commentIp) {
		this.commentIp = commentIp == null ? null : commentIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.ip_area
	 * @return  the value of t_comment.ip_area
	 * @mbg.generated
	 */
	public String getIpArea() {
		return ipArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.ip_area
	 * @param ipArea  the value for t_comment.ip_area
	 * @mbg.generated
	 */
	public void setIpArea(String ipArea) {
		this.ipArea = ipArea == null ? null : ipArea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.comment_content
	 * @return  the value of t_comment.comment_content
	 * @mbg.generated
	 */
	public String getCommentContent() {
		return commentContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.comment_content
	 * @param commentContent  the value for t_comment.comment_content
	 * @mbg.generated
	 */
	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent == null ? null : commentContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.comment_images
	 * @return  the value of t_comment.comment_images
	 * @mbg.generated
	 */
	public String getCommentImages() {
		return commentImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.comment_images
	 * @param commentImages  the value for t_comment.comment_images
	 * @mbg.generated
	 */
	public void setCommentImages(String commentImages) {
		this.commentImages = commentImages == null ? null : commentImages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.have_images
	 * @return  the value of t_comment.have_images
	 * @mbg.generated
	 */
	public Integer getHaveImages() {
		return haveImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.have_images
	 * @param haveImages  the value for t_comment.have_images
	 * @mbg.generated
	 */
	public void setHaveImages(Integer haveImages) {
		this.haveImages = haveImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.comment_status
	 * @return  the value of t_comment.comment_status
	 * @mbg.generated
	 */
	public Integer getCommentStatus() {
		return commentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.comment_status
	 * @param commentStatus  the value for t_comment.comment_status
	 * @mbg.generated
	 */
	public void setCommentStatus(Integer commentStatus) {
		this.commentStatus = commentStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.reply_total
	 * @return  the value of t_comment.reply_total
	 * @mbg.generated
	 */
	public Integer getReplyTotal() {
		return replyTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.reply_total
	 * @param replyTotal  the value for t_comment.reply_total
	 * @mbg.generated
	 */
	public void setReplyTotal(Integer replyTotal) {
		this.replyTotal = replyTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_comment.praise_total
	 * @return  the value of t_comment.praise_total
	 * @mbg.generated
	 */
	public Integer getPraiseTotal() {
		return praiseTotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_comment.praise_total
	 * @param praiseTotal  the value for t_comment.praise_total
	 * @mbg.generated
	 */
	public void setPraiseTotal(Integer praiseTotal) {
		this.praiseTotal = praiseTotal;
	}

	private Praise praise;

	public Praise getPraise() {
		return praise;
	}

	public void setPraise(Praise praise) {
		this.praise = praise;
	}

}