package com.coinMall.pojo;

import java.util.Date;

public class GoldLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.obtain_id
	 * @mbg.generated
	 */
	private Long obtainId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.rule_id
	 * @mbg.generated
	 */
	private Integer ruleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.obtain_time
	 * @mbg.generated
	 */
	private Date obtainTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.obtain_gold
	 * @mbg.generated
	 */
	private Double obtainGold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.platform_id
	 * @mbg.generated
	 */
	private Integer platformId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.module_id
	 * @mbg.generated
	 */
	private Integer moduleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gold_log.obtain_description
	 * @mbg.generated
	 */
	private String obtainDescription;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.obtain_id
	 * @return  the value of t_gold_log.obtain_id
	 * @mbg.generated
	 */
	public Long getObtainId() {
		return obtainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.obtain_id
	 * @param obtainId  the value for t_gold_log.obtain_id
	 * @mbg.generated
	 */
	public void setObtainId(Long obtainId) {
		this.obtainId = obtainId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.uid
	 * @return  the value of t_gold_log.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.uid
	 * @param uid  the value for t_gold_log.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.rule_id
	 * @return  the value of t_gold_log.rule_id
	 * @mbg.generated
	 */
	public Integer getRuleId() {
		return ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.rule_id
	 * @param ruleId  the value for t_gold_log.rule_id
	 * @mbg.generated
	 */
	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.obtain_time
	 * @return  the value of t_gold_log.obtain_time
	 * @mbg.generated
	 */
	public Date getObtainTime() {
		return obtainTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.obtain_time
	 * @param obtainTime  the value for t_gold_log.obtain_time
	 * @mbg.generated
	 */
	public void setObtainTime(Date obtainTime) {
		this.obtainTime = obtainTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.obtain_gold
	 * @return  the value of t_gold_log.obtain_gold
	 * @mbg.generated
	 */
	public Double getObtainGold() {
		return obtainGold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.obtain_gold
	 * @param obtainGold  the value for t_gold_log.obtain_gold
	 * @mbg.generated
	 */
	public void setObtainGold(Double obtainGold) {
		this.obtainGold = obtainGold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.platform_id
	 * @return  the value of t_gold_log.platform_id
	 * @mbg.generated
	 */
	public Integer getPlatformId() {
		return platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.platform_id
	 * @param platformId  the value for t_gold_log.platform_id
	 * @mbg.generated
	 */
	public void setPlatformId(Integer platformId) {
		this.platformId = platformId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.module_id
	 * @return  the value of t_gold_log.module_id
	 * @mbg.generated
	 */
	public Integer getModuleId() {
		return moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.module_id
	 * @param moduleId  the value for t_gold_log.module_id
	 * @mbg.generated
	 */
	public void setModuleId(Integer moduleId) {
		this.moduleId = moduleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gold_log.obtain_description
	 * @return  the value of t_gold_log.obtain_description
	 * @mbg.generated
	 */
	public String getObtainDescription() {
		return obtainDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gold_log.obtain_description
	 * @param obtainDescription  the value for t_gold_log.obtain_description
	 * @mbg.generated
	 */
	public void setObtainDescription(String obtainDescription) {
		this.obtainDescription = obtainDescription == null ? null : obtainDescription.trim();
	}
}