package com.coinMall.pojo;

public class GoldRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.rule_id
     *
     * @mbg.generated
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.platform_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.rule_description
     *
     * @mbg.generated
     */
    private String ruleDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.rule_min_value
     *
     * @mbg.generated
     */
    private Double ruleMinValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.rule_max_value
     *
     * @mbg.generated
     */
    private Double ruleMaxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.rule_average_value
     *
     * @mbg.generated
     */
    private Double ruleAverageValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.rule_type
     *
     * @mbg.generated
     */
    private Integer ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gold_rule.module_id
     *
     * @mbg.generated
     */
    private Integer moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.rule_id
     *
     * @return the value of t_gold_rule.rule_id
     *
     * @mbg.generated
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.rule_id
     *
     * @param ruleId the value for t_gold_rule.rule_id
     *
     * @mbg.generated
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.platform_id
     *
     * @return the value of t_gold_rule.platform_id
     *
     * @mbg.generated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.platform_id
     *
     * @param platformId the value for t_gold_rule.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.rule_description
     *
     * @return the value of t_gold_rule.rule_description
     *
     * @mbg.generated
     */
    public String getRuleDescription() {
        return ruleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.rule_description
     *
     * @param ruleDescription the value for t_gold_rule.rule_description
     *
     * @mbg.generated
     */
    public void setRuleDescription(String ruleDescription) {
        this.ruleDescription = ruleDescription == null ? null : ruleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.rule_min_value
     *
     * @return the value of t_gold_rule.rule_min_value
     *
     * @mbg.generated
     */
    public Double getRuleMinValue() {
        return ruleMinValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.rule_min_value
     *
     * @param ruleMinValue the value for t_gold_rule.rule_min_value
     *
     * @mbg.generated
     */
    public void setRuleMinValue(Double ruleMinValue) {
        this.ruleMinValue = ruleMinValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.rule_max_value
     *
     * @return the value of t_gold_rule.rule_max_value
     *
     * @mbg.generated
     */
    public Double getRuleMaxValue() {
        return ruleMaxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.rule_max_value
     *
     * @param ruleMaxValue the value for t_gold_rule.rule_max_value
     *
     * @mbg.generated
     */
    public void setRuleMaxValue(Double ruleMaxValue) {
        this.ruleMaxValue = ruleMaxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.rule_average_value
     *
     * @return the value of t_gold_rule.rule_average_value
     *
     * @mbg.generated
     */
    public Double getRuleAverageValue() {
        return ruleAverageValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.rule_average_value
     *
     * @param ruleAverageValue the value for t_gold_rule.rule_average_value
     *
     * @mbg.generated
     */
    public void setRuleAverageValue(Double ruleAverageValue) {
        this.ruleAverageValue = ruleAverageValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.rule_type
     *
     * @return the value of t_gold_rule.rule_type
     *
     * @mbg.generated
     */
    public Integer getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.rule_type
     *
     * @param ruleType the value for t_gold_rule.rule_type
     *
     * @mbg.generated
     */
    public void setRuleType(Integer ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gold_rule.module_id
     *
     * @return the value of t_gold_rule.module_id
     *
     * @mbg.generated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gold_rule.module_id
     *
     * @param moduleId the value for t_gold_rule.module_id
     *
     * @mbg.generated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
}