package com.coinMall.pojo;

import java.util.Date;

public class GoodsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_short_name
     *
     * @mbg.generated
     */
    private String goodsShortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_img
     *
     * @mbg.generated
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_description
     *
     * @mbg.generated
     */
    private String goodsDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_short_description
     *
     * @mbg.generated
     */
    private String goodsShortDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_amount
     *
     * @mbg.generated
     */
    private Double goodsAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_gold
     *
     * @mbg.generated
     */
    private Double goodsGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_total
     *
     * @mbg.generated
     */
    private Integer goodsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_browse_total
     *
     * @mbg.generated
     */
    private Integer goodsBrowseTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_exchange_total
     *
     * @mbg.generated
     */
    private Integer goodsExchangeTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_sort
     *
     * @mbg.generated
     */
    private Integer goodsSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_create_time
     *
     * @mbg.generated
     */
    private Date goodsCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_update_time
     *
     * @mbg.generated
     */
    private Date goodsUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_status
     *
     * @mbg.generated
     */
    private Integer goodsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_recommend
     *
     * @mbg.generated
     */
    private Integer goodsRecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.recommend_time
     *
     * @mbg.generated
     */
    private Date recommendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.recommend_image
     *
     * @mbg.generated
     */
    private String recommendImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_key_words
     *
     * @mbg.generated
     */
    private String goodsKeyWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_info.goods_detail
     *
     * @mbg.generated
     */
    private String goodsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_id
     *
     * @return the value of t_goods_info.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_id
     *
     * @param goodsId the value for t_goods_info.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.category_id
     *
     * @return the value of t_goods_info.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.category_id
     *
     * @param categoryId the value for t_goods_info.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_name
     *
     * @return the value of t_goods_info.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_name
     *
     * @param goodsName the value for t_goods_info.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_short_name
     *
     * @return the value of t_goods_info.goods_short_name
     *
     * @mbg.generated
     */
    public String getGoodsShortName() {
        return goodsShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_short_name
     *
     * @param goodsShortName the value for t_goods_info.goods_short_name
     *
     * @mbg.generated
     */
    public void setGoodsShortName(String goodsShortName) {
        this.goodsShortName = goodsShortName == null ? null : goodsShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_img
     *
     * @return the value of t_goods_info.goods_img
     *
     * @mbg.generated
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_img
     *
     * @param goodsImg the value for t_goods_info.goods_img
     *
     * @mbg.generated
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg == null ? null : goodsImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_description
     *
     * @return the value of t_goods_info.goods_description
     *
     * @mbg.generated
     */
    public String getGoodsDescription() {
        return goodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_description
     *
     * @param goodsDescription the value for t_goods_info.goods_description
     *
     * @mbg.generated
     */
    public void setGoodsDescription(String goodsDescription) {
        this.goodsDescription = goodsDescription == null ? null : goodsDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_short_description
     *
     * @return the value of t_goods_info.goods_short_description
     *
     * @mbg.generated
     */
    public String getGoodsShortDescription() {
        return goodsShortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_short_description
     *
     * @param goodsShortDescription the value for t_goods_info.goods_short_description
     *
     * @mbg.generated
     */
    public void setGoodsShortDescription(String goodsShortDescription) {
        this.goodsShortDescription = goodsShortDescription == null ? null : goodsShortDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_amount
     *
     * @return the value of t_goods_info.goods_amount
     *
     * @mbg.generated
     */
    public Double getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_amount
     *
     * @param goodsAmount the value for t_goods_info.goods_amount
     *
     * @mbg.generated
     */
    public void setGoodsAmount(Double goodsAmount) {
        this.goodsAmount = goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_gold
     *
     * @return the value of t_goods_info.goods_gold
     *
     * @mbg.generated
     */
    public Double getGoodsGold() {
        return goodsGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_gold
     *
     * @param goodsGold the value for t_goods_info.goods_gold
     *
     * @mbg.generated
     */
    public void setGoodsGold(Double goodsGold) {
        this.goodsGold = goodsGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_total
     *
     * @return the value of t_goods_info.goods_total
     *
     * @mbg.generated
     */
    public Integer getGoodsTotal() {
        return goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_total
     *
     * @param goodsTotal the value for t_goods_info.goods_total
     *
     * @mbg.generated
     */
    public void setGoodsTotal(Integer goodsTotal) {
        this.goodsTotal = goodsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_browse_total
     *
     * @return the value of t_goods_info.goods_browse_total
     *
     * @mbg.generated
     */
    public Integer getGoodsBrowseTotal() {
        return goodsBrowseTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_browse_total
     *
     * @param goodsBrowseTotal the value for t_goods_info.goods_browse_total
     *
     * @mbg.generated
     */
    public void setGoodsBrowseTotal(Integer goodsBrowseTotal) {
        this.goodsBrowseTotal = goodsBrowseTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_exchange_total
     *
     * @return the value of t_goods_info.goods_exchange_total
     *
     * @mbg.generated
     */
    public Integer getGoodsExchangeTotal() {
        return goodsExchangeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_exchange_total
     *
     * @param goodsExchangeTotal the value for t_goods_info.goods_exchange_total
     *
     * @mbg.generated
     */
    public void setGoodsExchangeTotal(Integer goodsExchangeTotal) {
        this.goodsExchangeTotal = goodsExchangeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_sort
     *
     * @return the value of t_goods_info.goods_sort
     *
     * @mbg.generated
     */
    public Integer getGoodsSort() {
        return goodsSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_sort
     *
     * @param goodsSort the value for t_goods_info.goods_sort
     *
     * @mbg.generated
     */
    public void setGoodsSort(Integer goodsSort) {
        this.goodsSort = goodsSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_create_time
     *
     * @return the value of t_goods_info.goods_create_time
     *
     * @mbg.generated
     */
    public Date getGoodsCreateTime() {
        return goodsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_create_time
     *
     * @param goodsCreateTime the value for t_goods_info.goods_create_time
     *
     * @mbg.generated
     */
    public void setGoodsCreateTime(Date goodsCreateTime) {
        this.goodsCreateTime = goodsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_update_time
     *
     * @return the value of t_goods_info.goods_update_time
     *
     * @mbg.generated
     */
    public Date getGoodsUpdateTime() {
        return goodsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_update_time
     *
     * @param goodsUpdateTime the value for t_goods_info.goods_update_time
     *
     * @mbg.generated
     */
    public void setGoodsUpdateTime(Date goodsUpdateTime) {
        this.goodsUpdateTime = goodsUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_status
     *
     * @return the value of t_goods_info.goods_status
     *
     * @mbg.generated
     */
    public Integer getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_status
     *
     * @param goodsStatus the value for t_goods_info.goods_status
     *
     * @mbg.generated
     */
    public void setGoodsStatus(Integer goodsStatus) {
        this.goodsStatus = goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_recommend
     *
     * @return the value of t_goods_info.goods_recommend
     *
     * @mbg.generated
     */
    public Integer getGoodsRecommend() {
        return goodsRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_recommend
     *
     * @param goodsRecommend the value for t_goods_info.goods_recommend
     *
     * @mbg.generated
     */
    public void setGoodsRecommend(Integer goodsRecommend) {
        this.goodsRecommend = goodsRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.recommend_time
     *
     * @return the value of t_goods_info.recommend_time
     *
     * @mbg.generated
     */
    public Date getRecommendTime() {
        return recommendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.recommend_time
     *
     * @param recommendTime the value for t_goods_info.recommend_time
     *
     * @mbg.generated
     */
    public void setRecommendTime(Date recommendTime) {
        this.recommendTime = recommendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.recommend_image
     *
     * @return the value of t_goods_info.recommend_image
     *
     * @mbg.generated
     */
    public String getRecommendImage() {
        return recommendImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.recommend_image
     *
     * @param recommendImage the value for t_goods_info.recommend_image
     *
     * @mbg.generated
     */
    public void setRecommendImage(String recommendImage) {
        this.recommendImage = recommendImage == null ? null : recommendImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_key_words
     *
     * @return the value of t_goods_info.goods_key_words
     *
     * @mbg.generated
     */
    public String getGoodsKeyWords() {
        return goodsKeyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_key_words
     *
     * @param goodsKeyWords the value for t_goods_info.goods_key_words
     *
     * @mbg.generated
     */
    public void setGoodsKeyWords(String goodsKeyWords) {
        this.goodsKeyWords = goodsKeyWords == null ? null : goodsKeyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_info.goods_detail
     *
     * @return the value of t_goods_info.goods_detail
     *
     * @mbg.generated
     */
    public String getGoodsDetail() {
        return goodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_info.goods_detail
     *
     * @param goodsDetail the value for t_goods_info.goods_detail
     *
     * @mbg.generated
     */
    public void setGoodsDetail(String goodsDetail) {
        this.goodsDetail = goodsDetail == null ? null : goodsDetail.trim();
    }
}