package com.coinMall.pojo;

public class GoodsImages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_images.images_id
	 * @mbg.generated
	 */
	private Integer imagesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_images.goods_id
	 * @mbg.generated
	 */
	private Long goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_images.images_src
	 * @mbg.generated
	 */
	private String imagesSrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_images.images_sort
	 * @mbg.generated
	 */
	private Integer imagesSort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_images.images_display
	 * @mbg.generated
	 */
	private Integer imagesDisplay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_goods_images.images_descirption
	 * @mbg.generated
	 */
	private String imagesDescirption;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_images.images_id
	 * @return  the value of t_goods_images.images_id
	 * @mbg.generated
	 */
	public Integer getImagesId() {
		return imagesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_images.images_id
	 * @param imagesId  the value for t_goods_images.images_id
	 * @mbg.generated
	 */
	public void setImagesId(Integer imagesId) {
		this.imagesId = imagesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_images.goods_id
	 * @return  the value of t_goods_images.goods_id
	 * @mbg.generated
	 */
	public Long getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_images.goods_id
	 * @param goodsId  the value for t_goods_images.goods_id
	 * @mbg.generated
	 */
	public void setGoodsId(Long goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_images.images_src
	 * @return  the value of t_goods_images.images_src
	 * @mbg.generated
	 */
	public String getImagesSrc() {
		return imagesSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_images.images_src
	 * @param imagesSrc  the value for t_goods_images.images_src
	 * @mbg.generated
	 */
	public void setImagesSrc(String imagesSrc) {
		this.imagesSrc = imagesSrc == null ? null : imagesSrc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_images.images_sort
	 * @return  the value of t_goods_images.images_sort
	 * @mbg.generated
	 */
	public Integer getImagesSort() {
		return imagesSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_images.images_sort
	 * @param imagesSort  the value for t_goods_images.images_sort
	 * @mbg.generated
	 */
	public void setImagesSort(Integer imagesSort) {
		this.imagesSort = imagesSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_images.images_display
	 * @return  the value of t_goods_images.images_display
	 * @mbg.generated
	 */
	public Integer getImagesDisplay() {
		return imagesDisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_images.images_display
	 * @param imagesDisplay  the value for t_goods_images.images_display
	 * @mbg.generated
	 */
	public void setImagesDisplay(Integer imagesDisplay) {
		this.imagesDisplay = imagesDisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_goods_images.images_descirption
	 * @return  the value of t_goods_images.images_descirption
	 * @mbg.generated
	 */
	public String getImagesDescirption() {
		return imagesDescirption;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_goods_images.images_descirption
	 * @param imagesDescirption  the value for t_goods_images.images_descirption
	 * @mbg.generated
	 */
	public void setImagesDescirption(String imagesDescirption) {
		this.imagesDescirption = imagesDescirption == null ? null : imagesDescirption.trim();
	}
}