package com.coinMall.pojo;

public class Module {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.module_id
     *
     * @mbg.generated
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.platform_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_module.module_name
     *
     * @mbg.generated
     */
    private String moduleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.module_id
     *
     * @return the value of t_module.module_id
     *
     * @mbg.generated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.module_id
     *
     * @param moduleId the value for t_module.module_id
     *
     * @mbg.generated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.platform_id
     *
     * @return the value of t_module.platform_id
     *
     * @mbg.generated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.platform_id
     *
     * @param platformId the value for t_module.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_module.module_name
     *
     * @return the value of t_module.module_name
     *
     * @mbg.generated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_module.module_name
     *
     * @param moduleName the value for t_module.module_name
     *
     * @mbg.generated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }
}