package com.coinMall.pojo;

import java.util.Date;

public class PlatformRechargeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_recharge_log.recharge_id
     *
     * @mbg.generated
     */
    private Integer rechargeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_recharge_log.platform_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_recharge_log.recharge_time
     *
     * @mbg.generated
     */
    private Date rechargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_recharge_log.recharge_amount
     *
     * @mbg.generated
     */
    private Double rechargeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_recharge_log.recharge_gold
     *
     * @mbg.generated
     */
    private Double rechargeGold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_recharge_log.recharge_ip
     *
     * @mbg.generated
     */
    private String rechargeIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_recharge_log.recharge_id
     *
     * @return the value of t_platform_recharge_log.recharge_id
     *
     * @mbg.generated
     */
    public Integer getRechargeId() {
        return rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_recharge_log.recharge_id
     *
     * @param rechargeId the value for t_platform_recharge_log.recharge_id
     *
     * @mbg.generated
     */
    public void setRechargeId(Integer rechargeId) {
        this.rechargeId = rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_recharge_log.platform_id
     *
     * @return the value of t_platform_recharge_log.platform_id
     *
     * @mbg.generated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_recharge_log.platform_id
     *
     * @param platformId the value for t_platform_recharge_log.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_recharge_log.recharge_time
     *
     * @return the value of t_platform_recharge_log.recharge_time
     *
     * @mbg.generated
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_recharge_log.recharge_time
     *
     * @param rechargeTime the value for t_platform_recharge_log.recharge_time
     *
     * @mbg.generated
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_recharge_log.recharge_amount
     *
     * @return the value of t_platform_recharge_log.recharge_amount
     *
     * @mbg.generated
     */
    public Double getRechargeAmount() {
        return rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_recharge_log.recharge_amount
     *
     * @param rechargeAmount the value for t_platform_recharge_log.recharge_amount
     *
     * @mbg.generated
     */
    public void setRechargeAmount(Double rechargeAmount) {
        this.rechargeAmount = rechargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_recharge_log.recharge_gold
     *
     * @return the value of t_platform_recharge_log.recharge_gold
     *
     * @mbg.generated
     */
    public Double getRechargeGold() {
        return rechargeGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_recharge_log.recharge_gold
     *
     * @param rechargeGold the value for t_platform_recharge_log.recharge_gold
     *
     * @mbg.generated
     */
    public void setRechargeGold(Double rechargeGold) {
        this.rechargeGold = rechargeGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_recharge_log.recharge_ip
     *
     * @return the value of t_platform_recharge_log.recharge_ip
     *
     * @mbg.generated
     */
    public String getRechargeIp() {
        return rechargeIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_recharge_log.recharge_ip
     *
     * @param rechargeIp the value for t_platform_recharge_log.recharge_ip
     *
     * @mbg.generated
     */
    public void setRechargeIp(String rechargeIp) {
        this.rechargeIp = rechargeIp == null ? null : rechargeIp.trim();
    }
}