package com.coinMall.pojo;

public class PlatformInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_info.platform_id
     *
     * @mbg.generated
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_info.platform_name
     *
     * @mbg.generated
     */
    private String platformName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_info.platform_type
     *
     * @mbg.generated
     */
    private Integer platformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_platform_info.platform_gold
     *
     * @mbg.generated
     */
    private Double platformGold;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_info.platform_id
     *
     * @return the value of t_platform_info.platform_id
     *
     * @mbg.generated
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_info.platform_id
     *
     * @param platformId the value for t_platform_info.platform_id
     *
     * @mbg.generated
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_info.platform_name
     *
     * @return the value of t_platform_info.platform_name
     *
     * @mbg.generated
     */
    public String getPlatformName() {
        return platformName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_info.platform_name
     *
     * @param platformName the value for t_platform_info.platform_name
     *
     * @mbg.generated
     */
    public void setPlatformName(String platformName) {
        this.platformName = platformName == null ? null : platformName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_info.platform_type
     *
     * @return the value of t_platform_info.platform_type
     *
     * @mbg.generated
     */
    public Integer getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_info.platform_type
     *
     * @param platformType the value for t_platform_info.platform_type
     *
     * @mbg.generated
     */
    public void setPlatformType(Integer platformType) {
        this.platformType = platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_platform_info.platform_gold
     *
     * @return the value of t_platform_info.platform_gold
     *
     * @mbg.generated
     */
    public Double getPlatformGold() {
        return platformGold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_platform_info.platform_gold
     *
     * @param platformGold the value for t_platform_info.platform_gold
     *
     * @mbg.generated
     */
    public void setPlatformGold(Double platformGold) {
        this.platformGold = platformGold;
    }
}