package com.coinMall.pojo;

public class Praise {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_praise.praise_id
	 * @mbg.generated
	 */
	private Long praiseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_praise.comment_id
	 * @mbg.generated
	 */
	private Long commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_praise.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_praise.praise_type
	 * @mbg.generated
	 */
	private Integer praiseType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_praise.praise_id
	 * @return  the value of t_praise.praise_id
	 * @mbg.generated
	 */
	public Long getPraiseId() {
		return praiseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_praise.praise_id
	 * @param praiseId  the value for t_praise.praise_id
	 * @mbg.generated
	 */
	public void setPraiseId(Long praiseId) {
		this.praiseId = praiseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_praise.comment_id
	 * @return  the value of t_praise.comment_id
	 * @mbg.generated
	 */
	public Long getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_praise.comment_id
	 * @param commentId  the value for t_praise.comment_id
	 * @mbg.generated
	 */
	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_praise.uid
	 * @return  the value of t_praise.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_praise.uid
	 * @param uid  the value for t_praise.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_praise.praise_type
	 * @return  the value of t_praise.praise_type
	 * @mbg.generated
	 */
	public Integer getPraiseType() {
		return praiseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_praise.praise_type
	 * @param praiseType  the value for t_praise.praise_type
	 * @mbg.generated
	 */
	public void setPraiseType(Integer praiseType) {
		this.praiseType = praiseType;
	}
}