package com.coinMall.pojo;

import java.util.Date;

public class ReceiptInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_id
	 * @mbg.generated
	 */
	private Integer receiptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_country
	 * @mbg.generated
	 */
	private String receiptCountry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_province
	 * @mbg.generated
	 */
	private String receiptProvince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_city
	 * @mbg.generated
	 */
	private String receiptCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_district
	 * @mbg.generated
	 */
	private String receiptDistrict;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_detail_address
	 * @mbg.generated
	 */
	private String receiptDetailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_zcode
	 * @mbg.generated
	 */
	private String receiptZcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_name
	 * @mbg.generated
	 */
	private String receiptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_phone
	 * @mbg.generated
	 */
	private String receiptPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_receipt_info.receipt_default
	 * @mbg.generated
	 */
	private Integer receiptDefault;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_id
	 * @return  the value of t_receipt_info.receipt_id
	 * @mbg.generated
	 */
	public Integer getReceiptId() {
		return receiptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_id
	 * @param receiptId  the value for t_receipt_info.receipt_id
	 * @mbg.generated
	 */
	public void setReceiptId(Integer receiptId) {
		this.receiptId = receiptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.uid
	 * @return  the value of t_receipt_info.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.uid
	 * @param uid  the value for t_receipt_info.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_country
	 * @return  the value of t_receipt_info.receipt_country
	 * @mbg.generated
	 */
	public String getReceiptCountry() {
		return receiptCountry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_country
	 * @param receiptCountry  the value for t_receipt_info.receipt_country
	 * @mbg.generated
	 */
	public void setReceiptCountry(String receiptCountry) {
		this.receiptCountry = receiptCountry == null ? null : receiptCountry.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_province
	 * @return  the value of t_receipt_info.receipt_province
	 * @mbg.generated
	 */
	public String getReceiptProvince() {
		return receiptProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_province
	 * @param receiptProvince  the value for t_receipt_info.receipt_province
	 * @mbg.generated
	 */
	public void setReceiptProvince(String receiptProvince) {
		this.receiptProvince = receiptProvince == null ? null : receiptProvince.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_city
	 * @return  the value of t_receipt_info.receipt_city
	 * @mbg.generated
	 */
	public String getReceiptCity() {
		return receiptCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_city
	 * @param receiptCity  the value for t_receipt_info.receipt_city
	 * @mbg.generated
	 */
	public void setReceiptCity(String receiptCity) {
		this.receiptCity = receiptCity == null ? null : receiptCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_district
	 * @return  the value of t_receipt_info.receipt_district
	 * @mbg.generated
	 */
	public String getReceiptDistrict() {
		return receiptDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_district
	 * @param receiptDistrict  the value for t_receipt_info.receipt_district
	 * @mbg.generated
	 */
	public void setReceiptDistrict(String receiptDistrict) {
		this.receiptDistrict = receiptDistrict == null ? null : receiptDistrict.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_detail_address
	 * @return  the value of t_receipt_info.receipt_detail_address
	 * @mbg.generated
	 */
	public String getReceiptDetailAddress() {
		return receiptDetailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_detail_address
	 * @param receiptDetailAddress  the value for t_receipt_info.receipt_detail_address
	 * @mbg.generated
	 */
	public void setReceiptDetailAddress(String receiptDetailAddress) {
		this.receiptDetailAddress = receiptDetailAddress == null ? null : receiptDetailAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_zcode
	 * @return  the value of t_receipt_info.receipt_zcode
	 * @mbg.generated
	 */
	public String getReceiptZcode() {
		return receiptZcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_zcode
	 * @param receiptZcode  the value for t_receipt_info.receipt_zcode
	 * @mbg.generated
	 */
	public void setReceiptZcode(String receiptZcode) {
		this.receiptZcode = receiptZcode == null ? null : receiptZcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_name
	 * @return  the value of t_receipt_info.receipt_name
	 * @mbg.generated
	 */
	public String getReceiptName() {
		return receiptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_name
	 * @param receiptName  the value for t_receipt_info.receipt_name
	 * @mbg.generated
	 */
	public void setReceiptName(String receiptName) {
		this.receiptName = receiptName == null ? null : receiptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_phone
	 * @return  the value of t_receipt_info.receipt_phone
	 * @mbg.generated
	 */
	public String getReceiptPhone() {
		return receiptPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_phone
	 * @param receiptPhone  the value for t_receipt_info.receipt_phone
	 * @mbg.generated
	 */
	public void setReceiptPhone(String receiptPhone) {
		this.receiptPhone = receiptPhone == null ? null : receiptPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_receipt_info.receipt_default
	 * @return  the value of t_receipt_info.receipt_default
	 * @mbg.generated
	 */
	public Integer getReceiptDefault() {
		return receiptDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_receipt_info.receipt_default
	 * @param receiptDefault  the value for t_receipt_info.receipt_default
	 * @mbg.generated
	 */
	public void setReceiptDefault(Integer receiptDefault) {
		this.receiptDefault = receiptDefault;
	}
}