package com.coinMall.pojo;

import java.util.Date;

public class ShopCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop_cart.cart_id
     *
     * @mbg.generated
     */
    private Long cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop_cart.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop_cart.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop_cart.stock_id
     *
     * @mbg.generated
     */
    private Long stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop_cart.cart_time
     *
     * @mbg.generated
     */
    private Date cartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop_cart.cart_total
     *
     * @mbg.generated
     */
    private Integer cartTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop_cart.cart_id
     *
     * @return the value of t_shop_cart.cart_id
     *
     * @mbg.generated
     */
    public Long getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop_cart.cart_id
     *
     * @param cartId the value for t_shop_cart.cart_id
     *
     * @mbg.generated
     */
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop_cart.uid
     *
     * @return the value of t_shop_cart.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop_cart.uid
     *
     * @param uid the value for t_shop_cart.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop_cart.goods_id
     *
     * @return the value of t_shop_cart.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop_cart.goods_id
     *
     * @param goodsId the value for t_shop_cart.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop_cart.stock_id
     *
     * @return the value of t_shop_cart.stock_id
     *
     * @mbg.generated
     */
    public Long getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop_cart.stock_id
     *
     * @param stockId the value for t_shop_cart.stock_id
     *
     * @mbg.generated
     */
    public void setStockId(Long stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop_cart.cart_time
     *
     * @return the value of t_shop_cart.cart_time
     *
     * @mbg.generated
     */
    public Date getCartTime() {
        return cartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop_cart.cart_time
     *
     * @param cartTime the value for t_shop_cart.cart_time
     *
     * @mbg.generated
     */
    public void setCartTime(Date cartTime) {
        this.cartTime = cartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop_cart.cart_total
     *
     * @return the value of t_shop_cart.cart_total
     *
     * @mbg.generated
     */
    public Integer getCartTotal() {
        return cartTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop_cart.cart_total
     *
     * @param cartTotal the value for t_shop_cart.cart_total
     *
     * @mbg.generated
     */
    public void setCartTotal(Integer cartTotal) {
        this.cartTotal = cartTotal;
    }
}